[package]
name = "portal"
version = "0.1.0"
authors = ["Simon Veilleux <sveilleux1@gmail.com>"]
publish = false

[[bin]]
name = "portal"
path = "portal/src/main.rs"

[dependencies]
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
webserver = { path = "portal/webserver" }
