[package]
name = "portal"
version = "0.1.0"
authors = ["Simon Veilleux <sveilleux1@gmail.com>"]
publish = false

[[bin]]
name = "portal"
path = "portal/src/main.rs"

[dependencies]
webserver = { path = "portal/webserver" }
